version: '3.8'

services:
  yessal-manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api.yessal.sn/api
        - VITE_DEV_PORT=4510
        - VITE_APP_NAME=Yessal Manager
        - VITE_APP_VERSION=1.0.0
        - VITE_DEV_MODE=false
        - VITE_LOG_LEVEL=error
    ports:
      - "4510:80"
    restart: unless-stopped
    networks:
      - yessal-network

networks:
  yessal-network:
    driver: bridge 