version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: yessal-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yessal
      MYSQL_USER: abdou
      MYSQL_PASSWORD: mdp
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - yessal-network

  yessal-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4520:4520"
    environment:
      - NODE_ENV=production
      - PORT=4520
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - yessal-network

volumes:
  mysql-data:

networks:
  yessal-network:
    driver: bridge